#!/usr/bin/env python3
"""
D2(b) - THE v1/v2 COMPARISON, from ONE script, ONE toggle
====================================================================
Runs the SAME 15 Problem A cases, on the SAME model, at the SAME
trial counts, through BOTH prompt versions - v1 (original shipped
rules text + original six-field descriptors + no extra validation)
and v2 (this team's rewrite) - via agent.run_case's prompt_version
argument (see agent.py's STRICT_VALIDATION and prompt.py's RULES_V1).

WHY THIS REPLACES THE EARLIER SEPARATE JSON FILES
dev_live_probe_v2_baseline.json / _v2_improved.json / _v2_final.json /
_v2_clean.json were each generated by a DIFFERENT snapshot of the
working tree, as bugs were found and fixed mid-experiment. Comparing
across them is comparing not-quite-the-same code, which is exactly the
kind of "measurement" D2(b)/D6 warns against. This script fixes that:
both sides run from the CURRENT code, differing ONLY in
prompt_version, in one process, writing ONE results file.

Costs real money - this is the live battery. At ~$0.002/call on
openai/gpt-4o-mini, the full run (15 cases x ~1.7 avg trials x 2
versions ~= 50 calls) costs under $0.15.

Usage:
    source <your key file>
    A2_BACKEND=live python3 dev_v1_v2_compare.py [model]
Writes dev_v1_v2_compare_results.json.
"""
import sys

import config
import harness
from agent import run_case


def _is_negative(expected):
    if not expected:
        return False
    return expected.get("expected_decision") in (
        "escalate", "request_document", "request_information")


def trials_for(cid, key):
    return 3 if _is_negative(key.get(cid)) else 1


def run_version(version, case_ids, key):
    approve = lambda action, payload: True
    rows = []
    for cid in case_ids:
        expected = key.get(cid)
        for trial in range(1, trials_for(cid, key) + 1):
            try:
                record = run_case(cid, problem="A", approve=approve,
                                  prompt_version=version)
            except Exception as error:
                print("  [%s] %-10s trial %d CRASHED: %r" % (version, cid, trial, error))
                rows.append({"case_id": cid, "trial": trial,
                            "expected_decision": expected.get("expected_decision") if expected else None,
                            "decision": None, "passed": False,
                            "fails": ["crashed: %r" % error],
                            "turns": None, "tokens_in": 0, "tokens_out": 0,
                            "cost_usd": 0.0, "stopped_by": "crash"})
                continue
            passed, fails = harness.code_check(record, expected) if expected else (None, ["no answer key row"])
            rows.append({
                "case_id": cid, "trial": trial,
                "family": expected.get("family") if expected else None,
                "expected_decision": expected.get("expected_decision") if expected else None,
                "decision": record.get("decision"),
                "trigger": record.get("trigger"),
                "passed": passed, "fails": fails,
                "turns": record["turns"],
                "final_rejections": record["final_rejections"],
                "tokens_in": record["tokens_in"],
                "tokens_out": record["tokens_out"],
                "cost_usd": record["cost_usd"],
                "stopped_by": record["stopped_by"],
                "guardrails_fired": record["guardrails_fired"],
            })
            print("  [%s] %-10s trial %d  turns=%d tokens=%d/%d cost=$%.5f decision=%-22s expected=%-22s %s"
                  % (version, cid, trial, record["turns"], record["tokens_in"],
                     record["tokens_out"], record["cost_usd"], record.get("decision"),
                     expected.get("expected_decision") if expected else "?",
                     "PASS" if passed else "FAIL" if passed is not None else "?"))
    return rows


def summarise(rows):
    passed = sum(1 for r in rows if r["passed"])
    graded = sum(1 for r in rows if r["passed"] is not None)
    tin = sum(r["tokens_in"] for r in rows)
    tout = sum(r["tokens_out"] for r in rows)
    cost = sum(r["cost_usd"] for r in rows)
    turns = sorted(r["turns"] for r in rows if r["turns"] is not None)
    return {
        "trials": len(rows), "pass": passed, "graded": graded,
        "pass_rate": passed / graded if graded else 0.0,
        "tokens_in_total": tin, "tokens_out_total": tout,
        "cost_usd_total": round(cost, 6),
        "median_turns": turns[len(turns) // 2] if turns else None,
        "max_turns": max(turns) if turns else None,
    }


def main(argv):
    if len(argv) > 1:
        config.MODEL = argv[1]
    print(config.summary())
    print("  D2(b) v1/v2 comparison - model=%s" % config.MODEL)
    print()

    key = harness.load_key("A")
    case_ids = harness.load_cases("A")

    results = {}
    for version in ("v1", "v2"):
        print("--- %s ---" % version)
        rows = run_version(version, case_ids, key)
        results[version] = {"rows": rows, "summary": summarise(rows)}
        print()

    print("=" * 68)
    print("  %-30s %10s %10s" % ("", "v1", "v2"))
    for field, fmt in (("pass_rate", "%.1f%%"), ("median_turns", "%s"),
                       ("max_turns", "%s"), ("cost_usd_total", "$%.4f")):
        v1 = results["v1"]["summary"][field]
        v2 = results["v2"]["summary"][field]
        if field == "pass_rate":
            v1, v2 = v1 * 100, v2 * 100
        print("  %-30s %10s %10s" % (field, fmt % v1, fmt % v2))
    print("=" * 68)

    import json
    with open("dev_v1_v2_compare_results.json", "w", encoding="utf-8") as fh:
        json.dump({"model": config.MODEL, "results": results}, fh,
                  indent=2, default=str)
    print("  wrote dev_v1_v2_compare_results.json (single source of truth -")
    print("  supersedes the earlier separate dev_live_probe_*.json files)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
